repos:
  -   repo: https://github.com/softwaremill/scala-pre-commit-hooks
      rev: v0.5.0
      hooks:
        -   id: sbt-unused-imports
            args: [--scope=test:compile]
        -   id: sbt-scalafmt-apply
            args: [--no-clean]
            stages: [pre-push]
