services:
  spark-emr:
    image: public.ecr.aws/emr-serverless/spark/emr-7.5.0:20241125
    volumes:
      - type: bind
        source: ./logging-conf
        target: /var/loggingConfiguration/spark
      - type: bind
        source: ../spark-sample-app/target/scala-2.12
        target: /app
      - type: bind
        source: ./spark-conf
        target: /etc/spark/conf
      - type: bind
        source: ${PPL_JAR}
        target: /usr/lib/spark/jars/ppl-spark-integration.jar
    command: driver --class MyApp /app/myapp_2.12-1.0.jar
