#!/usr/bin/bash

RED="\033[0;31m"
NC="\033[0m"

cd ~/workplace/opensearch-spark || exit
mkdir -p scripts/lib

echo "Preparing artifacts"
if ! sbt scalafmtAll assembly standaloneCosmetic/publishM2 sparkPPLCosmetic/publishM2 sparkSqlApplicationCosmetic/publishM2 ; then
    printf "%sAborting!%s" "$RED" "$NC"
    exit 1
fi

cd scripts || exit

echo "Copying jars"
VER=1.0.0
cp ~/.m2/repository/org/opensearch/opensearch-spark-ppl_2.12/$VER-SNAPSHOT/opensearch-spark-ppl_2.12-$VER-SNAPSHOT.jar lib/opensearch-spark-ppl_2.12-$VER.jar
cp ~/.m2/repository/org/opensearch/opensearch-spark-sql-application_2.12/$VER-SNAPSHOT/opensearch-spark-sql-application_2.12-$VER-SNAPSHOT.jar lib/opensearch-spark-sql-application_2.12-$VER.jar
cp ~/.m2/repository/org/opensearch/opensearch-spark-standalone_2.12/$VER-SNAPSHOT/opensearch-spark-standalone_2.12-$VER-SNAPSHOT.jar lib/opensearch-spark-standalone_2.12-$VER.jar
cp ~/workplace/extern/spark-deps/src/SearchServicesManagedFlintEMRImageJars/jars/SearchServicesFireflowerHelperForFlint-1.0.jar lib/SearchServicesFireflowerHelperForFlint-1.0.jar

echo "Done!"
