#!/usr/bin/sh

account_id=905418019649
domain_name=flint-sawiddis-2-17

policy="{\"Version\": \"2012-10-17\",\"Statement\": [{\"Effect\": \"Allow\",\"Principal\": {\"AWS\": [\"*\"]},\"Action\": [\"es:*\"],\"Resource\": \"arn:aws:es:us-west-2:${account_id}:domain/${domain_name}/*\"}]}"

aws opensearch create-domain \
    --endpoint-url https://es-release.us-west-2.amazonaws.com \
    --no-verify-ssl \
    --domain-name $domain_name \
    --ebs-options EBSEnabled=true,VolumeType=gp2,VolumeSize=30 \
    --engine-version OpenSearch_2.17 \
    --advanced-security-options Enabled=true,InternalUserDatabaseEnabled=true,MasterUserOptions='{MasterUserName="admin",MasterUserPassword="Welcome@123"}' \
    --node-to-node-encryption-options Enabled=true \
    --encryption-at-rest-options Enabled=true,KmsKeyId=c7464c0e-263c-4505-b84e-9b7a4d65c044 \
    --domain-endpoint-options EnforceHTTPS=true \
    --region us-west-2 \
    --cluster-config InstanceType=m5.large.search,InstanceCount=1,DedicatedMasterEnabled=false,ZoneAwarenessEnabled=false \
    --access-policies "${policy}"
