name: Link Checker

on:
  pull_request:
  push:
    branches:
      - 'main'
      - '[1-9]+.[0-9x]+'

jobs:
  linkchecker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@master
        with:
          args: --accept=200,403,429,999 --exclude-mail **/*.html **/*.md **/*.txt --exclude-file .lychee.excludes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
